apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-03-10T22:41:54Z"
  name: simplenode-canary
  resourceVersion: "136233"
  selfLink: /api/v1/namespaces/simpleproject-prod/services/simplenode
  uid: 576c12fa-6320-11ea-b7d9-0a28257f1614
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: simplenode
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
